[project]
authors = ["Josuan Calderon, Michael Hess (Pixi packaging)"]
channels = ["conda-forge"]
description = "Pixi environment for running code from the TACI paper and pipeline"
name = "TACI"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
numpy = "1.26.4"
ipython = ">=8.37.0,<9"
ipykernel = ">=6.29.5,<7"
h5py = ">=3.14.0,<4"
matplotlib = ">=3.10.3,<4"
scikit-learn = ">=1.7.0,<2"
pandas = ">=2.3.0,<3"
scipy = ">=1.15.2,<2"
statsmodels = ">=0.14.4,<0.15"
pip = ">=25.1.1,<26"

[pypi-dependencies]
tensorflow = { version = ">=2.14.0, <2.18.0", extras = ["and-cuda"] }
keras-tcn = {git = "https://github.com/philipperemy/keras-tcn", rev = "30a765c1daad74514874a6fb363fd428298af899"}
